// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePurrfectPaw.API.DbContexts;

namespace ThePurrfectPaw.API.Migrations
{
    [DbContext(typeof(ThePurrfectPawContext))]
    [Migration("20200619015717_Testing_2")]
    partial class Testing_2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThePurrfectPaw.API.Entities.Posting", b =>
                {
                    b.Property<int>("PostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("PostingId");

                    b.ToTable("Postings");

                    b.HasData(
                        new
                        {
                            PostingId = 1,
                            IsPublic = true,
                            PostDate = new DateTime(2020, 5, 12, 5, 15, 33, 0, DateTimeKind.Unspecified),
                            Title = "Testing Posting 1"
                        },
                        new
                        {
                            PostingId = 2,
                            IsPublic = true,
                            PostDate = new DateTime(2020, 6, 29, 12, 30, 33, 0, DateTimeKind.Unspecified),
                            Title = "Testing Posting 2"
                        },
                        new
                        {
                            PostingId = 3,
                            IsPublic = false,
                            PostDate = new DateTime(2020, 6, 18, 21, 57, 17, 621, DateTimeKind.Local).AddTicks(8347),
                            Title = "Testing Posting 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
