// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThePurrfectPaw.API.DbContexts;

namespace ThePurrfectPaw.API.Migrations
{
    [DbContext(typeof(ThePurrfectPawContext))]
    [Migration("20200619023403_AddedShelterModel")]
    partial class AddedShelterModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ThePurrfectPaw.API.Entities.Posting", b =>
                {
                    b.Property<int>("PostingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShelterId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("PostingId");

                    b.HasIndex("ShelterId");

                    b.ToTable("Postings");

                    b.HasData(
                        new
                        {
                            PostingId = 1,
                            IsPublic = true,
                            PostDate = new DateTime(2020, 5, 12, 5, 15, 33, 0, DateTimeKind.Unspecified),
                            ShelterId = 1,
                            Title = "Testing Posting 1"
                        },
                        new
                        {
                            PostingId = 2,
                            IsPublic = true,
                            PostDate = new DateTime(2020, 6, 5, 12, 30, 33, 0, DateTimeKind.Unspecified),
                            ShelterId = 1,
                            Title = "Testing Posting 2"
                        },
                        new
                        {
                            PostingId = 3,
                            IsPublic = false,
                            PostDate = new DateTime(2020, 6, 18, 22, 34, 2, 805, DateTimeKind.Local).AddTicks(1653),
                            ShelterId = 1,
                            Title = "Testing Posting 3"
                        });
                });

            modelBuilder.Entity("ThePurrfectPaw.API.Entities.Shelter", b =>
                {
                    b.Property<int>("ShelterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ShelterId");

                    b.ToTable("Shelters");

                    b.HasData(
                        new
                        {
                            ShelterId = 1,
                            Name = "Verona Street Animal Society"
                        });
                });

            modelBuilder.Entity("ThePurrfectPaw.API.Entities.Posting", b =>
                {
                    b.HasOne("ThePurrfectPaw.API.Entities.Shelter", "Shelter")
                        .WithMany("Postings")
                        .HasForeignKey("ShelterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
